package client;

import cn.itcast.mybatis.domain.ContractProductC;
import cn.itcast.mybatis.domain.ContractProductCExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContractProductCMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_C
     *
     * @mbggenerated Tue Aug 12 10:21:44 CST 2014
     */
    int countByExample(ContractProductCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_C
     *
     * @mbggenerated Tue Aug 12 10:21:44 CST 2014
     */
    int deleteByExample(ContractProductCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_C
     *
     * @mbggenerated Tue Aug 12 10:21:44 CST 2014
     */
    int deleteByPrimaryKey(String contractProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_C
     *
     * @mbggenerated Tue Aug 12 10:21:44 CST 2014
     */
    int insert(ContractProductC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_C
     *
     * @mbggenerated Tue Aug 12 10:21:44 CST 2014
     */
    int insertSelective(ContractProductC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_C
     *
     * @mbggenerated Tue Aug 12 10:21:44 CST 2014
     */
    List<ContractProductC> selectByExample(ContractProductCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_C
     *
     * @mbggenerated Tue Aug 12 10:21:44 CST 2014
     */
    ContractProductC selectByPrimaryKey(String contractProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_C
     *
     * @mbggenerated Tue Aug 12 10:21:44 CST 2014
     */
    int updateByExampleSelective(@Param("record") ContractProductC record, @Param("example") ContractProductCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_C
     *
     * @mbggenerated Tue Aug 12 10:21:44 CST 2014
     */
    int updateByExample(@Param("record") ContractProductC record, @Param("example") ContractProductCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_C
     *
     * @mbggenerated Tue Aug 12 10:21:44 CST 2014
     */
    int updateByPrimaryKeySelective(ContractProductC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_C
     *
     * @mbggenerated Tue Aug 12 10:21:44 CST 2014
     */
    int updateByPrimaryKey(ContractProductC record);
}