package cn.itcast.jk.domain;


public class ExtCproduct {
    private String id;

    public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
    private String contractProductId;
    private String factoryId;
    private String factoryName;
    private Integer ctype;
    private String productNo;
    private String productImage;
    private String productDesc;
    private Integer cnumber;
    private String packingUnit;
    private Double price;
    private Double amount;
    private String productRequest;
    private Integer orderNo;
    public String getContractProductId() {
        return contractProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_CPRODUCT_C.CONTRACT_PRODUCT_ID
     *
     * @param contractProductId the value for EXT_CPRODUCT_C.CONTRACT_PRODUCT_ID
     *
     * @mbggenerated Tue Aug 12 16:03:15 CST 2014
     */
    public void setContractProductId(String contractProductId) {
        this.contractProductId = contractProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.FACTORY_ID
     *
     * @return the value of EXT_CPRODUCT_C.FACTORY_ID
     *
     * @mbggenerated Tue Aug 12 16:03:15 CST 2014
     */
    public String getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_CPRODUCT_C.FACTORY_ID
     *
     * @param factoryId the value for EXT_CPRODUCT_C.FACTORY_ID
     *
     * @mbggenerated Tue Aug 12 16:03:15 CST 2014
     */
    public void setFactoryId(String factoryId) {
        this.factoryId = factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.FACTORY_NAME
     *
     * @return the value of EXT_CPRODUCT_C.FACTORY_NAME
     *
     * @mbggenerated Tue Aug 12 16:03:15 CST 2014
     */
    public String getFactoryName() {
        return factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_CPRODUCT_C.FACTORY_NAME
     *
     * @param factoryName the value for EXT_CPRODUCT_C.FACTORY_NAME
     *
     * @mbggenerated Tue Aug 12 16:03:15 CST 2014
     */
    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.CTYPE
     *
     * @return the value of EXT_CPRODUCT_C.CTYPE
     *
     * @mbggenerated Tue Aug 12 16:03:15 CST 2014
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.PRODUCT_NO
     *
     * @return the value of EXT_CPRODUCT_C.PRODUCT_NO
     *
     * @mbggenerated Tue Aug 12 16:03:15 CST 2014
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_CPRODUCT_C.PRODUCT_NO
     *
     * @param productNo the value for EXT_CPRODUCT_C.PRODUCT_NO
     *
     * @mbggenerated Tue Aug 12 16:03:15 CST 2014
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.PRODUCT_IMAGE
     *
     * @return the value of EXT_CPRODUCT_C.PRODUCT_IMAGE
     *
     * @mbggenerated Tue Aug 12 16:03:15 CST 2014
     */
    public String getProductImage() {
        return productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_CPRODUCT_C.PRODUCT_IMAGE
     *
     * @param productImage the value for EXT_CPRODUCT_C.PRODUCT_IMAGE
     *
     * @mbggenerated Tue Aug 12 16:03:15 CST 2014
     */
    public void setProductImage(String productImage) {
        this.productImage = productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.PRODUCT_DESC
     *
     * @return the value of EXT_CPRODUCT_C.PRODUCT_DESC
     *
     * @mbggenerated Tue Aug 12 16:03:15 CST 2014
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_CPRODUCT_C.PRODUCT_DESC
     *
     * @param productDesc the value for EXT_CPRODUCT_C.PRODUCT_DESC
     *
     * @mbggenerated Tue Aug 12 16:03:15 CST 2014
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.CNUMBER
     *
     * @return the value of EXT_CPRODUCT_C.CNUMBER
     *
     * @mbggenerated Tue Aug 12 16:03:15 CST 2014
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.PACKING_UNIT
     *
     * @return the value of EXT_CPRODUCT_C.PACKING_UNIT
     *
     * @mbggenerated Tue Aug 12 16:03:15 CST 2014
     */
    public String getPackingUnit() {
        return packingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_CPRODUCT_C.PACKING_UNIT
     *
     * @param packingUnit the value for EXT_CPRODUCT_C.PACKING_UNIT
     *
     * @mbggenerated Tue Aug 12 16:03:15 CST 2014
     */
    public void setPackingUnit(String packingUnit) {
        this.packingUnit = packingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.PRICE
     *
     * @return the value of EXT_CPRODUCT_C.PRICE
     *
     * @mbggenerated Tue Aug 12 16:03:15 CST 2014
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.PRODUCT_REQUEST
     *
     * @return the value of EXT_CPRODUCT_C.PRODUCT_REQUEST
     *
     * @mbggenerated Tue Aug 12 16:03:15 CST 2014
     */
    public String getProductRequest() {
        return productRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_CPRODUCT_C.PRODUCT_REQUEST
     *
     * @param productRequest the value for EXT_CPRODUCT_C.PRODUCT_REQUEST
     *
     * @mbggenerated Tue Aug 12 16:03:15 CST 2014
     */
    public void setProductRequest(String productRequest) {
        this.productRequest = productRequest;
    }

	public Integer getCtype() {
		return ctype;
	}

	public void setCtype(Integer ctype) {
		this.ctype = ctype;
	}

	public Integer getCnumber() {
		return cnumber;
	}

	public void setCnumber(Integer cnumber) {
		this.cnumber = cnumber;
	}

	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Double getAmount() {
		return amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public Integer getOrderNo() {
		return orderNo;
	}

	public void setOrderNo(Integer orderNo) {
		this.orderNo = orderNo;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.ORDER_NO
     *
     * @return the value of EXT_CPRODUCT_C.ORDER_NO
     *
     * @mbggenerated Tue Aug 12 16:03:15 CST 2014
     */
    
}